GET http://localhost:9000/books/7

###

GET http://localhost:9000/cart/add

###

GET http://localhost:9000/wishlist
Content-Type: application/json


###

POST http://localhost:5000/post
Content-Type: application/json

{
    "title": "String",
    "author": "String",
    "publication_year": 1999,
    "genre": ["String"],
    "description": "String",
    "cover_image": "String",
    "price": 100,
}
